"""add gdpr enabled to bot config

Revision ID: 049cf37da3d0
Revises: 558dc232cf03
Create Date: 2026-06-23 18:18:32.368745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '049cf37da3d0'
down_revision: Union[str, None] = '558dc232cf03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_configs', sa.Column('gdpr_enabled', sa.Boolean(), server_default='false', nullable=False, comment='Whether GDPR PII masking is enabled for exports'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_configs', 'gdpr_enabled')
    # ### end Alembic commands ###
