"""add_tone_to_bot_config

Revision ID: 1778481510e1
Revises: 45a616eb72a8
Create Date: 2026-06-11 19:28:41.946974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1778481510e1'
down_revision: Union[str, None] = '45a616eb72a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_configs', sa.Column('tone', sa.String(length=50), nullable=True, comment='Conversational tone: professional, friendly, casual, formal'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_configs', 'tone')
    # ### end Alembic commands ###
