"""add_custom_mongo_fields_to_bot_config

Revision ID: 1921ed3fc2f2
Revises: d1e1e802a861
Create Date: 2026-07-10 16:03:19.454687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1921ed3fc2f2'
down_revision: Union[str, None] = 'd1e1e802a861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_configs', sa.Column('use_custom_mongo', sa.Boolean(), server_default='false', nullable=False, comment='Whether the bot uses a custom MongoDB Atlas instance for data storage'))
    op.add_column('bot_configs', sa.Column('mongo_uri', sa.Text(), nullable=True, comment='Encrypted MongoDB connection URI'))
    op.add_column('bot_configs', sa.Column('mongo_db_name', sa.String(length=100), nullable=True, comment='MongoDB database name'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_configs', 'mongo_db_name')
    op.drop_column('bot_configs', 'mongo_uri')
    op.drop_column('bot_configs', 'use_custom_mongo')
    # ### end Alembic commands ###
