"""create_url_crawls_table

Revision ID: 19df32a8cd6d
Revises: 762e429bdd5b
Create Date: 2026-06-12 14:53:24.880764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19df32a8cd6d'
down_revision: Union[str, None] = '762e429bdd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_crawls',
    sa.Column('bot_id', sa.UUID(), nullable=False, comment='Bot associated with this crawl'),
    sa.Column('start_url', sa.String(length=500), nullable=False, comment='Initial seed URL to start crawling from'),
    sa.Column('crawl_depth', sa.Integer(), server_default='1', nullable=False, comment='Max recursion depth for crawler'),
    sa.Column('status', sa.Enum('pending', 'crawling', 'completed', 'failed', name='url_crawl_status'), server_default='pending', nullable=False, comment='Current execution status of the crawl'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the crawl request was initiated'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_crawls_bot_id'), 'url_crawls', ['bot_id'], unique=False)
    op.create_index(op.f('ix_url_crawls_id'), 'url_crawls', ['id'], unique=False)
    op.create_index(op.f('ix_url_crawls_status'), 'url_crawls', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_crawls_status'), table_name='url_crawls')
    op.drop_index(op.f('ix_url_crawls_id'), table_name='url_crawls')
    op.drop_index(op.f('ix_url_crawls_bot_id'), table_name='url_crawls')
    op.drop_table('url_crawls')
    # ### end Alembic commands ###
