"""create_feedback_ratings_table

Revision ID: 2251dcb39339
Revises: c6fb8cbe5739
Create Date: 2026-06-23 16:04:18.323719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2251dcb39339'
down_revision: Union[str, None] = 'c6fb8cbe5739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_ratings',
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='Conversation session this feedback is associated with'),
    sa.Column('message_id', sa.UUID(), nullable=False, comment='Specific message inside the conversation that this feedback is for'),
    sa.Column('rating', sa.Enum('thumbs_up', 'thumbs_down', name='feedback_rating_value'), nullable=False, comment='Rating value: thumbs_up or thumbs_down'),
    sa.Column('feedback_text', sa.Text(), nullable=True, comment='Optional detailed text feedback explaining the rating'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when feedback was submitted'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_ratings_conversation_id'), 'feedback_ratings', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_feedback_ratings_id'), 'feedback_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_ratings_message_id'), 'feedback_ratings', ['message_id'], unique=False)
    op.create_index(op.f('ix_feedback_ratings_rating'), 'feedback_ratings', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_ratings_rating'), table_name='feedback_ratings')
    op.drop_index(op.f('ix_feedback_ratings_message_id'), table_name='feedback_ratings')
    op.drop_index(op.f('ix_feedback_ratings_id'), table_name='feedback_ratings')
    op.drop_index(op.f('ix_feedback_ratings_conversation_id'), table_name='feedback_ratings')
    op.drop_table('feedback_ratings')
    
    # Drop enum type explicitly
    op.execute("DROP TYPE feedback_rating_value")
    # ### end Alembic commands ###
