"""create_bot_config_model

Revision ID: 45a616eb72a8
Revises: 4bd53ffd9d2d
Create Date: 2026-06-11 19:16:18.388782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45a616eb72a8'
down_revision: Union[str, None] = '4bd53ffd9d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_configs',
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment="System-level prompt that shapes the bot's persona and behaviour"),
    sa.Column('welcome_message', sa.Text(), nullable=True, comment='First message shown to users when a conversation starts'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='LLM model identifier, e.g. gpt-4o-mini, claude-3-haiku'),
    sa.Column('temperature', sa.Float(), nullable=False, comment='Sampling temperature (0.0 = deterministic, 2.0 = creative)'),
    sa.Column('max_tokens', sa.Integer(), nullable=False, comment='Maximum tokens the LLM is allowed to generate per response'),
    sa.Column('top_k', sa.Integer(), nullable=False, comment='Number of knowledge-base chunks retrieved per query'),
    sa.Column('similarity_threshold', sa.Float(), nullable=False, comment='Minimum cosine similarity score for a chunk to be used'),
    sa.Column('is_streaming', sa.Boolean(), nullable=False, comment='Stream token-by-token responses to the client'),
    sa.Column('fallback_message', sa.Text(), nullable=True, comment='Message shown when the bot cannot answer a query'),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Freeform JSONB bag for future settings not yet modelled as columns'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_configs_bot_id'), 'bot_configs', ['bot_id'], unique=True)
    op.create_index(op.f('ix_bot_configs_id'), 'bot_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_configs_id'), table_name='bot_configs')
    op.drop_index(op.f('ix_bot_configs_bot_id'), table_name='bot_configs')
    op.drop_table('bot_configs')
    # ### end Alembic commands ###
