"""create_bot_version_model

Revision ID: 4bd53ffd9d2d
Revises: ef022b68c02f
Create Date: 2026-06-11 19:12:32.489920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bd53ffd9d2d'
down_revision: Union[str, None] = 'ef022b68c02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_versions',
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full configuration snapshot of the bot at this version'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', 'version_number', name='uq_bot_versions_bot_id_version')
    )
    op.create_index(op.f('ix_bot_versions_bot_id'), 'bot_versions', ['bot_id'], unique=False)
    op.create_index(op.f('ix_bot_versions_id'), 'bot_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_versions_id'), table_name='bot_versions')
    op.drop_index(op.f('ix_bot_versions_bot_id'), table_name='bot_versions')
    op.drop_table('bot_versions')
    # ### end Alembic commands ###
