"""create_ingestion_jobs_table

Revision ID: 762e429bdd5b
Revises: f7a3af601ab3
Create Date: 2026-06-12 12:03:30.277438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762e429bdd5b'
down_revision: Union[str, None] = 'f7a3af601ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_jobs',
    sa.Column('source_id', sa.UUID(), nullable=False, comment='Knowledge source this ingestion job processes'),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='ingestion_job_status'), server_default='queued', nullable=False, comment='Current status of the ingestion execution'),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False, comment='Percentage progress of the ingestion execution (0-100)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Detailed error message if the job failed'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of when processing started'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of when processing completed or failed'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_id'), 'ingestion_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_source_id'), 'ingestion_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_status'), 'ingestion_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_jobs_status'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_source_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    # ### end Alembic commands ###
