"""drop_sql_message_chunk_tables

Revision ID: a07ec767df94
Revises: 1921ed3fc2f2
Create Date: 2026-07-11 11:15:05.327629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a07ec767df94'
down_revision: Union[str, None] = '1921ed3fc2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feedback_ratings_message_id_fkey', 'feedback_ratings', type_='foreignkey')
    op.drop_index('ix_embeddings_chunk_id', table_name='embeddings')
    op.drop_index('ix_embeddings_embedding_vector', table_name='embeddings', postgresql_using='hnsw')
    op.drop_index('ix_embeddings_id', table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_index('ix_messages_conversation_id_created_at', table_name='messages')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_index('ix_messages_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_source_chunks_id', table_name='source_chunks')
    op.drop_index('ix_source_chunks_source_id', table_name='source_chunks')
    op.drop_table('source_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('feedback_ratings_message_id_fkey', 'feedback_ratings', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_table('source_chunks',
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=False, comment='Knowledge source this chunk belongs to'),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False, comment='Index of the chunk within the source'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='Actual text content of the chunk'),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='Number of tokens in the content'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Timestamp of chunk creation'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], name='source_chunks_source_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='source_chunks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_source_chunks_source_id', 'source_chunks', ['source_id'], unique=False)
    op.create_index('ix_source_chunks_id', 'source_chunks', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment="Sender identity: 'user' or 'bot'"),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='Text content of the message'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='messages_conversation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='messages_pkey')
    )
    op.create_index('ix_messages_id', 'messages', ['id'], unique=False)
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_conversation_id_created_at', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=False, comment='Source chunk associated with this embedding'),
    sa.Column('embedding_vector', sa.NullType(), autoincrement=False, nullable=False, comment='1536-dimensional embedding vector'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Timestamp of embedding creation'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['source_chunks.id'], name='embeddings_chunk_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='embeddings_pkey')
    )
    op.create_index('ix_embeddings_id', 'embeddings', ['id'], unique=False)
    op.create_index('ix_embeddings_embedding_vector', 'embeddings', ['embedding_vector'], unique=False, postgresql_using='hnsw')
    op.create_index('ix_embeddings_chunk_id', 'embeddings', ['chunk_id'], unique=False)
    # ### end Alembic commands ###
