"""create_analytics_events_table

Revision ID: b1718d57dd99
Revises: ed487208261e
Create Date: 2026-06-12 11:47:46.943212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1718d57dd99'
down_revision: Union[str, None] = 'ed487208261e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('bot_id', sa.UUID(), nullable=False, comment='Bot this tracking event belongs to'),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='Conversation session (WidgetSession) this event is associated with'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='Type of event: conversation_started, message_sent, conversation_ended'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary event payload / metadata'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of when the event occurred'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['widget_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_bot_id'), 'analytics_events', ['bot_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_conversation_id'), 'analytics_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_id'), 'analytics_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_events_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_conversation_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_bot_id'), table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
