"""add_browser_info_to_conversations

Revision ID: c59b95261a29
Revises: 743bd92c17fb
Create Date: 2026-06-12 07:32:16.644107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c59b95261a29'
down_revision: Union[str, None] = '743bd92c17fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('browser_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Metadata about the visitor browser, OS, and viewport sizes'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'browser_info')
    # ### end Alembic commands ###
