"""update_analytics_events_model

Revision ID: c6fb8cbe5739
Revises: d107126ad327
Create Date: 2026-06-23 16:01:43.144715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6fb8cbe5739'
down_revision: Union[str, None] = 'd107126ad327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type explicitly for Postgres
    op.execute("CREATE TYPE analytics_event_type AS ENUM ('conversation_started', 'message_sent', 'bot_response', 'feedback_submitted')")
    
    op.add_column('analytics_events', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary event payload / metadata'))
    op.alter_column('analytics_events', 'conversation_id',
               existing_type=sa.UUID(),
               comment='Conversation session this event is associated with',
               existing_comment='Conversation session (WidgetSession) this event is associated with',
               existing_nullable=False)
    op.alter_column('analytics_events', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('conversation_started', 'message_sent', 'bot_response', 'feedback_submitted', name='analytics_event_type'),
               comment='Type of event: conversation_started, message_sent, bot_response, feedback_submitted',
               existing_comment='Type of event: conversation_started, message_sent, conversation_ended',
               existing_nullable=False,
               postgresql_using='event_type::analytics_event_type')
    op.drop_constraint('analytics_events_conversation_id_fkey', 'analytics_events', type_='foreignkey')
    op.create_foreign_key(None, 'analytics_events', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('analytics_events', 'payload')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_events', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Arbitrary event payload / metadata'))
    op.drop_constraint(None, 'analytics_events', type_='foreignkey')
    op.create_foreign_key('analytics_events_conversation_id_fkey', 'analytics_events', 'widget_sessions', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('analytics_events', 'event_type',
               existing_type=sa.Enum('conversation_started', 'message_sent', 'bot_response', 'feedback_submitted', name='analytics_event_type'),
               type_=sa.VARCHAR(length=50),
               comment='Type of event: conversation_started, message_sent, conversation_ended',
               existing_comment='Type of event: conversation_started, message_sent, bot_response, feedback_submitted',
               existing_nullable=False)
    op.alter_column('analytics_events', 'conversation_id',
               existing_type=sa.UUID(),
               comment='Conversation session (WidgetSession) this event is associated with',
               existing_comment='Conversation session this event is associated with',
               existing_nullable=False)
    op.drop_column('analytics_events', 'metadata')
    
    # Drop enum type explicitly
    op.execute("DROP TYPE analytics_event_type")
    # ### end Alembic commands ###
