"""create_export_jobs_table

Revision ID: ccdcaeb24474
Revises: 2251dcb39339
Create Date: 2026-06-23 16:18:38.763006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccdcaeb24474'
down_revision: Union[str, None] = '2251dcb39339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_jobs',
    sa.Column('bot_id', sa.UUID(), nullable=False, comment='Bot whose data is being exported'),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False, comment='Filter start date of the exported records'),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False, comment='Filter end date of the exported records'),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='export_job_status'), server_default='pending', nullable=False, comment='Current execution state of the export process'),
    sa.Column('file_path', sa.String(length=512), nullable=True, comment='Path to the generated export archive file'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the export was requested'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_jobs_bot_id'), 'export_jobs', ['bot_id'], unique=False)
    op.create_index(op.f('ix_export_jobs_id'), 'export_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_export_jobs_status'), 'export_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_jobs_status'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_id'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_bot_id'), table_name='export_jobs')
    op.drop_table('export_jobs')
    
    # Drop enum type explicitly
    op.execute("DROP TYPE export_job_status")
    # ### end Alembic commands ###
