"""create_embeddings_table

Revision ID: d107126ad327
Revises: 0a3a147bd070
Create Date: 2026-06-23 12:59:17.049400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'd107126ad327'
down_revision: Union[str, None] = '0a3a147bd070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('source_chunks',

    sa.Column('source_id', sa.UUID(), nullable=False, comment='Knowledge source this chunk belongs to'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Index of the chunk within the source'),
    sa.Column('content', sa.Text(), nullable=False, comment='Actual text content of the chunk'),
    sa.Column('token_count', sa.Integer(), nullable=False, comment='Number of tokens in the content'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of chunk creation'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_chunks_id'), 'source_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_source_chunks_source_id'), 'source_chunks', ['source_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('chunk_id', sa.UUID(), nullable=False, comment='Source chunk associated with this embedding'),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False, comment='1536-dimensional embedding vector'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of embedding creation'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['source_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_chunk_id'), 'embeddings', ['chunk_id'], unique=False)
    op.create_index('ix_embeddings_embedding_vector', 'embeddings', ['embedding_vector'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding_vector': 'vector_cosine_ops'})
    op.create_index(op.f('ix_embeddings_id'), 'embeddings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_id'), table_name='embeddings')
    op.drop_index('ix_embeddings_embedding_vector', table_name='embeddings', postgresql_using='hnsw', postgresql_ops={'embedding_vector': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_embeddings_chunk_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_source_chunks_source_id'), table_name='source_chunks')
    op.drop_index(op.f('ix_source_chunks_id'), table_name='source_chunks')
    op.drop_table('source_chunks')
    # ### end Alembic commands ###
