"""create_bot_managers_table

Revision ID: d1e1e802a861
Revises: 29b8062b2af3
Create Date: 2026-06-24 14:14:17.965357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e1e802a861'
down_revision: Union[str, None] = '29b8062b2af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_managers',
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_managers_bot_id'), 'bot_managers', ['bot_id'], unique=False)
    op.create_index(op.f('ix_bot_managers_created_at'), 'bot_managers', ['created_at'], unique=False)
    op.create_index(op.f('ix_bot_managers_id'), 'bot_managers', ['id'], unique=False)
    op.create_index(op.f('ix_bot_managers_user_id'), 'bot_managers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_managers_user_id'), table_name='bot_managers')
    op.drop_index(op.f('ix_bot_managers_id'), table_name='bot_managers')
    op.drop_index(op.f('ix_bot_managers_created_at'), table_name='bot_managers')
    op.drop_index(op.f('ix_bot_managers_bot_id'), table_name='bot_managers')
    op.drop_table('bot_managers')
    # ### end Alembic commands ###
