"""create_widget_sessions_table

Revision ID: ed487208261e
Revises: c59b95261a29
Create Date: 2026-06-12 10:39:00.900173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed487208261e'
down_revision: Union[str, None] = 'c59b95261a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_sessions',
    sa.Column('bot_id', sa.UUID(), nullable=False, comment='Bot this session belongs to'),
    sa.Column('visitor_session_id', sa.String(length=128), nullable=False, comment='Opaque visitor-supplied or server-generated session token. No PII – used only to correlate multiple requests within one visit.'),
    sa.Column('status', sa.Enum('active', 'closed', name='widget_session_status'), server_default='active', nullable=False, comment='Current lifecycle state of the session'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the visitor first opened the widget'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last time this session record was modified'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widget_sessions_bot_id'), 'widget_sessions', ['bot_id'], unique=False)
    op.create_index(op.f('ix_widget_sessions_id'), 'widget_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_widget_sessions_status'), 'widget_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_widget_sessions_visitor_session_id'), 'widget_sessions', ['visitor_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_widget_sessions_visitor_session_id'), table_name='widget_sessions')
    op.drop_index(op.f('ix_widget_sessions_status'), table_name='widget_sessions')
    op.drop_index(op.f('ix_widget_sessions_id'), table_name='widget_sessions')
    op.drop_index(op.f('ix_widget_sessions_bot_id'), table_name='widget_sessions')
    op.drop_table('widget_sessions')
    # Drop the PostgreSQL ENUM type created alongside the table
    sa.Enum(name='widget_session_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
