"""optimize_indexes_and_timestamps

Revision ID: f5dad9b9646a
Revises: 049cf37da3d0
Create Date: 2026-06-23 18:25:30.954963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5dad9b9646a'
down_revision: Union[str, None] = '049cf37da3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_bot_configs_created_at'), 'bot_configs', ['created_at'], unique=False)
    op.create_index(op.f('ix_bots_created_at'), 'bots', ['created_at'], unique=False)
    op.create_index('ix_conversations_bot_id_created_at', 'conversations', ['bot_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_ratings_created_at'), 'feedback_ratings', ['created_at'], unique=False)
    op.create_index('ix_messages_conversation_id_created_at', 'messages', ['conversation_id', sa.literal_column('created_at ASC')], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index('ix_messages_conversation_id_created_at', table_name='messages')
    op.drop_index(op.f('ix_feedback_ratings_created_at'), table_name='feedback_ratings')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_index('ix_conversations_bot_id_created_at', table_name='conversations')
    op.drop_index(op.f('ix_bots_created_at'), table_name='bots')
    op.drop_index(op.f('ix_bot_configs_created_at'), table_name='bot_configs')
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='analytics_events')
    # ### end Alembic commands ###
