"""create_knowledge_sources_table

Revision ID: f7a3af601ab3
Revises: b1718d57dd99
Create Date: 2026-06-12 12:00:01.259759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a3af601ab3'
down_revision: Union[str, None] = 'b1718d57dd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_sources',
    sa.Column('bot_id', sa.UUID(), nullable=False, comment='Bot this knowledge source belongs to'),
    sa.Column('source_type', sa.Enum('pdf', 'docx', 'url', name='knowledge_source_type'), nullable=False, comment='Type of knowledge source: pdf, docx, or url'),
    sa.Column('source_name', sa.String(length=255), nullable=False, comment='Human readable name of the source (e.g. filename or web title)'),
    sa.Column('file_path', sa.String(length=512), nullable=True, comment='Path to file on disk (for docx, pdf)'),
    sa.Column('url', sa.String(length=2048), nullable=True, comment='Scraped URL (for web sources)'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='Size of source file in bytes'),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='knowledge_source_status'), server_default='queued', nullable=False, comment='Current processing status: queued, processing, completed, failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of source creation'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sources_bot_id'), 'knowledge_sources', ['bot_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_id'), 'knowledge_sources', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_source_type'), 'knowledge_sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_status'), 'knowledge_sources', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_sources_status'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_source_type'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_bot_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    # ### end Alembic commands ###
